### ISSUE TITLE
service 启动错误

### ISSUE THREAD

**Issue by BloodElf** [starudream/miyoushe-task#1]
以 service 模式启动的时候报错，麻烦大佬看看是什么问题，万分感谢~

![image](https://github.com/starudream/miyoushe-task/assets/5360927/6c54412e-2932-4827-bb84-b2166be2b718)

**Comment by starudream** [comment]
可以先尝试命令 `./miyoushe-task --config /data/app/miyoushe-task.yaml account list` 运行试试

**Comment by starudream** [comment]
closed https://github.com/starudream/miyoushe-task/commit/902b0c3bf905b154660dec8e42842f7755b771d7
