### ISSUE TITLE
游戏签到失败，米游社任务正常

### ISSUE THREAD

**Issue by JinzeShi** [starudream/miyoushe-task#10]
签到报错：ERR job/game.go:155 dm error: dm is not configured
sign game record: {GameId:2 GameName:原神 RoleName:S** RoleUid:1** HasSigned:false IsRisky:true IsSuccess:false Verify:10 Award:}

**Comment by starudream** [comment]
米游社有相关风控，目前也没觉得方法，只能使用打码平台
