### ISSUE TITLE
可以加入未定事件簿吗？

### ISSUE THREAD

**Issue by Gnaix-39** [starudream/miyoushe-task#12]

**Comment by starudream** [comment]
这个版本 [v1.4.1](https://github.com/starudream/miyoushe-task/releases/tag/v1.4.1) 加上了

> 因为我没有对应的游戏和角色，没办法进行测试，成功与否欢迎留言。

**Comment by Gnaix-39** [comment]
![PixPin_2024-09-27_10-21-57](https://github.com/user-attachments/assets/3a81ae88-cf00-40cd-ac39-de6d4b789cae)
失败了(；´д｀)ゞ：WRN game biz nxx_cn not supported

**Comment by starudream** [comment]
下载 [v1.4.1](https://github.com/starudream/miyoushe-task/releases/tag/v1.4.1) 试试

**Comment by Gnaix-39** [comment]
噢，不好意思！我没有核对版本号sorry。我下载了[v1.4.1]貌似依然失败。
![Uploading PixPin_2024-09-27_10-29-21.png…]()

**Comment by starudream** [comment]
我刚才下了游戏试了一下，v1.4.1 是可以签到未定的。

我看你执行的命令是 `miyoushe-task sign game xxx` 可能指向了别的二进制，不清楚是不是这个原因。

你可以用 `miyoushe-task -v` 检查版本 或者执行 `./miyoushe-task sign game` 再尝试一下。

**Comment by Gnaix-39** [comment]
非常感谢！这次成功了，辛苦你为我下载并测试！[比心(*´・ｖ・)]”
