### ISSUE TITLE
大大能适配青龙面板进行使用吗？

### ISSUE THREAD

**Issue by LGenshin** [starudream/miyoushe-task#3]
https://github.com/whyour/qinglong
![image](https://github.com/starudream/miyoushe-task/assets/64765482/cf8c3a05-c506-478b-b5e4-4daea94ac8bb)

**Comment by starudream** [comment]
二进制文件可以在 release 下载：https://github.com/starudream/miyoushe-task/releases/latest

登陆之后生成配置文件后，手动调用游戏签到功能即可

```shell
miyoushe-task --config miyoushe-task.yaml sign game <account phone>
```
