### ISSUE TITLE
绝区零无法签到

### ISSUE THREAD

**Issue by half-drop** [starudream/miyoushe-task#7]
三天前就不能自动签到了。在相同的网络状况下手机上签到是正常的
![{_DR 9_MA})UJP~FA`%9YXK](https://github.com/user-attachments/assets/6dabb7f2-10f9-4787-8d8c-5a8fa85aaa0b)

**Comment by starudream** [comment]
v1.3.2 已修复

> 不好意思，绝区零我退坑了，没触发这个问题。
