### ISSUE TITLE
验证码接入

### ISSUE THREAD

**Issue by amadeus5201** [starudream/miyoushe-task#9]
可以接入shanmite/ocr_api_server验证码识别吗

**Comment by starudream** [comment]
是这个吗？https://github.com/sml2h3/ddddocr-fastapi

**Comment by starudream** [comment]
是这个吗？https://github.com/shanmiteko/ocr_api_server

这个好像就是个识别大模型，如何接入`极验`还需做另外的开发，似乎有点麻烦。
